def countNuqFreq(seq):
    tmpFreqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuq in seq:
        if nuq in tmpFreqDict:
            tmpFreqDict[nuq] += 1
    return tmpFreqDict

dna_seq = "AGCAATTCTATTCAACATGGGTATAACGCAAACCATCGCGCACTCTCAATGACTGGCCCATCCCTGAATAAGTCTTACTGAGTTCGCCTTGGAAACATTACTCAACCGCGTTTAACGAGCAAGGAACTCCAGCTCCTTGCCCCGCAAATCGGCTGGGAGACTACGAGAACTCCGTGTATCAATCGAAATAGTGAGACAAACCCTTTACATCTTTCGCTCCACCCGCGGTCAAGAGGATATATTGCGAGCCTGAGATCTGATAATATTAGGTTCCAGGAGGGACCATTATTGGTTGATGGTTGAATATGCCCATAGAGCCTCGGCGAAACGGCATAGAGTTAGAAATCCTGCATGCTGTGCTGTTAACTAGAGCAGTCCCTCTTCAAAGAAGTGAAATGTTTTCTCATAGGGGAAACCGAGAAAACTGATTGTAACCGCAGATATGCCTTACACAACAATAAGTAGCCTAGACCCACGTAATGTCGATGTACATTGTTCGAGAGTCGCAGGGATTCTACCTGTAGCTATAGCTAGGCATACTCGGGACACATACATTCTACAGGCTACTTCCGGTACCCGGATAGGACGGCGAACATATGTAAACTCGACCCCAAATGGCGGGATAGGAAAATGAATCAACGGCTCGACTCCCACATAGCGGACGGAGAAATGCTACCTTAGAGACGACTTGAGGCAACGCCGCCCAACAAACCACGGGATGAACTGCTGTATACAGTGATGTATATGGACATTCCATATTAAGGTATTAGGAGACTCAGCACGCTCTTTATATTAGTCTAAGGC"
result = countNuqFreq(dna_seq)
print(' '.join([str(val) for key, val in result.items()]))